baseURL = ""
languageCode = "en-us"
title = "OfficeGeek"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

paginate = 2

[taxonomies]
  kategorier = 'kategorier'
[permalinks]
  kategorier = "/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params]
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
  logo = "/images/logo.svg"
  logo_footer = "/images/logo.svg"
  copyright = "Lorem ipsum is placeholder text commonly used. Copyright © 2022 All Rights Reserved"
  author = "OfficeGeek"
  github = "#"
  ogimage = "/images/og.png"
  sitename = "OfficeGeek"
  twitter = "#"
